### PR TITLE
Commonjs

### PR DESCRIPTION
**Pull request by jasonLaster**
* drop amd 
* drop licenses
* replace devtools/client/shared/vendor/react with react
* switch exports.Foo to module.exports = Foo

### CODE REVIEW

**Comment by nchevobbe** [comment]
I know it's not use for now in m-c, but one thing to keep in mind for later is that the JSON Viewer, which use the Reps too, uses AMD modules.
There are already some issue with that due to L10N so eventually the JSON View will move to use something else, but we'll have to be careful until then if we bundle this for use in m-c

**Comment by jasonLaster** [comment]
Ahh - yeah. Sorry, I meant to write something up here.

I hope that we can update the webpack build so that it can also export an AMD build that the viewer can consume.

The goal is to have a clean development environment :)

**Comment by nchevobbe** [comment]
👍

**Comment by jasonLaster** [comment]
Merging this, ofcourse if we can't get the jsonviewer to work we'll revert!

**Pull request merged**
